# Generated by Django 6.0.4 on 2026-04-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heartbeatlog',
            options={'ordering': ['-ran_at'], 'verbose_name': 'heartbeat log', 'verbose_name_plural': 'heartbeat logs'},
        ),
        migrations.AlterModelOptions(
            name='rawmessage',
            options={'ordering': ['-received_at'], 'verbose_name': 'raw message', 'verbose_name_plural': 'raw messages'},
        ),
        migrations.AlterModelOptions(
            name='sourcefailure',
            options={'ordering': ['-occurred_at'], 'verbose_name': 'source failure', 'verbose_name_plural': 'source failures'},
        ),
    ]
