# Generated by Django 6.0.4 on 2026-04-19 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_suggested_tags_alter_event_organizer'),
        ('ingestion', '0002_alter_heartbeatlog_options_alter_rawmessage_options_and_more'),
        ('organizers', '0007_rename_organizer_to_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedSender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.CharField(max_length=100, unique=True)),
                ('telegram_handle', models.CharField(blank=True, max_length=100)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'approved sender',
                'verbose_name_plural': 'approved senders',
            },
        ),
        migrations.CreateModel(
            name='ExtractionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('model_name', models.CharField(max_length=100)),
                ('prompt_version', models.CharField(max_length=50)),
                ('raw_response', models.JSONField()),
                ('extracted_draft', models.JSONField(blank=True, default=dict)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'extraction attempt',
                'verbose_name_plural': 'extraction attempts',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.AddField(
            model_name='rawmessage',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='rawmessage',
            name='extraction_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('extracted', 'Extracted'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('needs_review', 'Needs review')], default='pending'),
        ),
        migrations.AddConstraint(
            model_name='rawmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('message_id__gt', '')), fields=('source_type', 'channel_id', 'message_id'), name='rawmessage_dedup_source_channel_message'),
        ),
        migrations.AddField(
            model_name='approvedsender',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizers.profile'),
        ),
        migrations.AddField(
            model_name='extractionattempt',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraction_attempts', to='events.event'),
        ),
        migrations.AddField(
            model_name='extractionattempt',
            name='raw_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='ingestion.rawmessage'),
        ),
    ]
