# Generated by Django 6.0.6 on 2026-09-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0006_approvedsender_fk_to_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmessage',
            name='collect_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rawmessage',
            name='extraction_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('extracted', 'Extracted'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('needs_review', 'Needs review'), ('duplicate', 'Duplicate of an existing event')], default='pending'),
        ),
        migrations.AlterField(
            model_name='rawmessage',
            name='source_type',
            field=models.CharField(choices=[('telegram_bot_forward', 'Telegram bot forward'), ('telegram_telethon', 'Telegram public channel, group or forum topic (user session)'), ('telegram_private_channel', 'Telegram private channel (user session)'), ('telegram_private_group', 'Telegram private group or forum topic (user session)'), ('website', 'Organizer website'), ('email_submission', 'Email submission'), ('web_form', 'Web form')]),
        ),
    ]
