# Generated by Django 6.0.8 on 2026-10-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0007_collected_feeds'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistCreditSuppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_key', models.CharField(max_length=200)),
                ('channel_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'artist credit suppression',
                'verbose_name_plural': 'artist credit suppressions',
                'constraints': [models.UniqueConstraint(fields=('name_key', 'channel_id'), name='artist_suppression_one_per_name_source')],
            },
        ),
    ]
