# Generated by Django 6.0.8 on 2026-10-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0008_artist_credit_removal'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionattempt',
            name='post_kind',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='extractionattempt',
            name='wrote',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
