# Generated by Django 6.0.4 on 2026-04-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['name'], 'verbose_name': 'venue', 'verbose_name_plural': 'venues'},
        ),
    ]
