# Generated by Django 6.0.8 on 2026-10-02 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0015_claimintent_message'),
        ('venues', '0002_alter_venue_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='run_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venues_run', to='organizers.profile'),
        ),
    ]
