# Generated by Django 6.0.4 on 2026-04-17 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('organizers', '0001_initial'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('theme', 'Theme'), ('format', 'Format'), ('identity', 'Identity'), ('bubble', 'Bubble')])),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('price_min_cents', models.IntegerField(blank=True, null=True)),
                ('price_max_cents', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('is_free', models.BooleanField(default=False)),
                ('sliding_scale', models.BooleanField(default=False)),
                ('external_url', models.URLField(blank=True)),
                ('tickets_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Needs review'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='organizers.organizer')),
                ('raw_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingestion.rawmessage')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='venues.venue')),
                ('tags', models.ManyToManyField(blank=True, related_name='events', to='events.tag')),
            ],
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/')),
                ('alt', models.CharField(blank=True, max_length=300)),
                ('is_cover', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.event')),
            ],
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'start'], name='events_even_status_336136_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organizer', 'start'], name='events_even_organiz_12b36e_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('organizer', 'slug'), name='event_slug_unique_per_organizer'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('organizer', 'start', 'title'), name='event_dup_guard_org_start_title'),
        ),
    ]
