# Generated by Django 6.0.4 on 2026-04-17 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('ingestion', '0002_alter_heartbeatlog_options_alter_rawmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start'], 'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
        migrations.AlterModelOptions(
            name='eventimage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'event image', 'verbose_name_plural': 'event images'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['label'], 'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
        migrations.AlterField(
            model_name='event',
            name='raw_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_events', to='ingestion.rawmessage'),
        ),
    ]
