# Generated by Django 6.0.4 on 2026-04-19 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options_alter_eventimage_options_and_more'),
        ('organizers', '0002_alter_organizer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='suggested_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='organizers.organizer'),
        ),
    ]
