# Generated by Django 6.0.4 on 2026-05-12 (kb-n0y: FK → M2M data-preserving migration)

import django.db.models.deletion
from django.db import migrations, models


def migrate_organizer_fk_to_eventorganizer(apps, schema_editor):
    """
    Data migration: for every Event with organizer_id IS NOT NULL,
    create an EventOrganizer(event, profile, is_primary=True, order=0).
    This preserves the FK association in the new through-table.
    """
    Event = apps.get_model("events", "Event")
    EventOrganizer = apps.get_model("events", "EventOrganizer")

    rows = []
    for event in Event.objects.filter(organizer__isnull=False).select_related("organizer"):
        rows.append(
            EventOrganizer(
                event=event,
                profile=event.organizer,
                is_primary=True,
                order=0,
            )
        )
    if rows:
        EventOrganizer.objects.bulk_create(rows)


def reverse_eventorganizer_to_fk(apps, schema_editor):
    """
    Reverse migration: restore Event.organizer FK from EventOrganizer primary rows.
    Note: this writes back to the organizer_id column which is re-added by the
    reverse migration infrastructure. Only restores is_primary=True rows.
    """
    Event = apps.get_model("events", "Event")
    EventOrganizer = apps.get_model("events", "EventOrganizer")

    for eo in EventOrganizer.objects.filter(is_primary=True).select_related("profile"):
        Event.objects.filter(pk=eo.event_id).update(organizer=eo.profile)


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_fk_to_profile'),
        ('organizers', '0007_rename_organizer_to_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventOrganizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'event organizer',
                'verbose_name_plural': 'event organizers',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='event',
            name='event_slug_unique_per_organizer',
        ),
        migrations.RemoveConstraint(
            model_name='event',
            name='event_dup_guard_org_start_title',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_organiz_12b36e_idx',
        ),
        migrations.AddField(
            model_name='eventorganizer',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_organizer_set', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventorganizer',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_organizer_set', to='organizers.profile'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='events_organized', through='events.EventOrganizer', through_fields=('event', 'profile'), to='organizers.profile'),
        ),
        # Data migration: copy FK associations to EventOrganizer through-table
        migrations.RunPython(
            migrate_organizer_fk_to_eventorganizer,
            reverse_code=reverse_eventorganizer_to_fk,
        ),
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
        migrations.AddConstraint(
            model_name='eventorganizer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('event',), name='event_organizer_one_primary_per_event'),
        ),
    ]
