# Generated by Django 6.0.4 on 2026-05-12 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_eventorganizer_and_more'),
        ('organizers', '0007_rename_organizer_to_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFacilitator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_facilitator_set', to='events.event')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facilitated_event_set', to='organizers.profile')),
            ],
            options={
                'verbose_name': 'event facilitator',
                'verbose_name_plural': 'event facilitators',
                'ordering': ['order', 'id'],
                'unique_together': {('event', 'profile')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='facilitators',
            field=models.ManyToManyField(blank=True, related_name='events_facilitated', through='events.EventFacilitator', through_fields=('event', 'profile'), to='organizers.profile'),
        ),
    ]
