# Generated by Django 6.0.4 on 2026-05-26 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='age_restriction',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum age for attendees; null = no age restriction.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='attendee_questions',
            field=models.JSONField(blank=True, default=list, help_text='RESERVED: screening questions asked at event entry / check-in. Behavior: RSVP+screening epic.'),
        ),
        migrations.AddField(
            model_name='event',
            name='buyer_questions',
            field=models.JSONField(blank=True, default=list, help_text="RESERVED: screening questions asked at ticket purchase (e.g., [{'question': 'Have you attended before?', 'type': 'bool'}]). Behavior: RSVP+screening epic."),
        ),
        migrations.AddField(
            model_name='event',
            name='content_warnings',
            field=models.JSONField(blank=True, default=list, help_text="List of content warning strings (e.g., ['nudity', 'bdsm'])."),
        ),
        migrations.AddField(
            model_name='event',
            name='dress_code',
            field=models.CharField(blank=True, help_text="Dress code for the event (e.g., 'Fetish attire required').", max_length=300),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_parent',
            field=models.ForeignKey(blank=True, help_text='RESERVED: FK to the canonical recurring event this instance was generated from. null = original / standalone. Behavior: recurring-events epic.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrence_instances', to='events.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_rule',
            field=models.CharField(blank=True, help_text="RESERVED: iCal RRULE string for recurring events (e.g., 'FREQ=WEEKLY;BYDAY=SA'). null = one-time event. Behavior: recurring-events epic.", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_types',
            field=models.JSONField(blank=True, default=list, help_text="RESERVED: full ticket type taxonomy (e.g., [{'name': 'Early Bird', 'price_cents': 1500, 'capacity': 20}]). Behavior: ticketing epic (ADR-015)."),
        ),
    ]
