# Generated by Django 6.0.4 on 2026-05-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_age_restriction_event_attendee_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, choices=[('play_party', 'Play Party'), ('workshop', 'Workshop'), ('munch', 'Munch'), ('performance', 'Performance'), ('social', 'Social'), ('festival', 'Festival'), ('other', 'Other')], help_text='Event category (v0 vocabulary).', max_length=50),
        ),
    ]
