# Generated by Django 6.0.6 on 2026-09-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0015_add_event_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="start_time_unknown",
            field=models.BooleanField(default=False),
        ),
    ]
