# Generated by Django 6.0.8 on 2026-10-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_event_start_time_unknown'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_note',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
