# Generated by Django 6.0.8 on 2026-10-02 08:42

from django.db import migrations, models

import venues.address


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0017_event_location_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="location_note",
            field=models.CharField(blank=True, max_length=200, validators=[venues.address.validate_no_street_address]),
        ),
    ]
