# Generated by Django 6.0.8 on 2026-10-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0020_eventartist_backfill_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventorganizer",
            name="attribution",
            field=models.CharField(
                blank=True,
                choices=[("explicit", "named in the text"), ("publisher", "the publishing source")],
                max_length=10,
            ),
        ),
    ]
