# Generated by Django 6.0.8 on 2026-10-02 16:04

import django.db.models.deletion
from django.db import migrations, models


def move_collected_urls_to_links(apps, schema_editor):
    """A collected event's external_url came from its source: it becomes that source's link row (ADR-007 D11)."""
    Event = apps.get_model("events", "Event")
    EventLink = apps.get_model("events", "EventLink")
    for event in Event.objects.exclude(raw_message=None).exclude(external_url=""):
        EventLink.objects.get_or_create(event=event, url=event.external_url, raw_message_id=event.raw_message_id)
        event.external_url = ""
        event.save(update_fields=["external_url"])


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_eventorganizer_attribution'),
        ('ingestion', '0009_presence_timezone_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='possible_duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='possible_duplicates', to='events.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='presence',
            field=models.CharField(choices=[('in_person', 'In person'), ('online', 'Online'), ('hybrid', 'In person and online')], default='in_person', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='timezone',
            field=models.CharField(default='Europe/Berlin', max_length=64),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, choices=[('play_party', 'Play Party'), ('workshop', 'Workshop'), ('munch', 'Munch'), ('performance', 'Performance'), ('social', 'Social'), ('festival', 'Festival'), ('talk', 'Talk'), ('other', 'Other')], help_text='Event category (v0 vocabulary).', max_length=50),
        ),
        migrations.CreateModel(
            name='EventLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='events.event')),
                ('raw_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_links', to='ingestion.rawmessage')),
            ],
            options={
                'verbose_name': 'event link',
                'verbose_name_plural': 'event links',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('event', 'url', 'raw_message'), name='eventlink_one_per_url_source')],
            },
        ),
        migrations.RunPython(move_collected_urls_to_links, migrations.RunPython.noop),
    ]
