# Generated by Django 6.0.8 on 2026-10-02 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_presence_timezone_links'),
        ('ingestion', '0009_presence_timezone_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventimage',
            name='raw_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_images', to='ingestion.rawmessage'),
        ),
    ]
