services:
  app:
    ports:
      - "8000:8000"
      - "5678:5678"  # Debugger port
    volumes:
      - .:/app
      - /app/.venv
    command: ["sh", "-c", "uv run python -m debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000"]

  qcluster:
    ports:
      - "6900:6900"
    command: ["sh", "-c", "uv run python -m debugpy --listen 0.0.0.0:6900 manage.py qcluster"]
