services:
  app:
    restart: unless-stopped
    command:
      - gunicorn
      - a_core.wsgi:application
      - --bind=0.0.0.0:8000
      - --workers=3
      - --access-logfile=-
      - --error-logfile=-

  qcluster:
    restart: unless-stopped

  bot:
    restart: unless-stopped

  db:
    restart: unless-stopped
    volumes:
      - type: bind
        source: /opt/switch-berlin/db
        target: /var/lib/postgresql/data

volumes:
  postgres_data: !reset null
