# Generated by Django 6.0.4 on 2026-05-26 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0014_event_age_restriction_event_attendee_questions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(help_text='Hook / headline for this post.', max_length=300)),
                ('body', models.TextField(help_text='Post body — canonical post content, not derived from event.description.')),
                ('imagery', models.JSONField(blank=True, default=None, help_text='List of image references/URLs for this post.', null=True)),
                ('cta', models.CharField(blank=True, help_text='Call-to-action text or URL (e.g., link to listing or Switch event page).', max_length=500)),
                ('voice', models.CharField(blank=True, help_text="Voice/tone intended for this post (e.g., 'playful', 'formal').", max_length=100)),
                ('sequence_order', models.PositiveIntegerField(blank=True, help_text='RESERVED: ordinal position of this Post within a multi-Post campaign sequence. null = standalone post (no sequence). Behavior: campaign-sequence epic.', null=True)),
                ('lifecycle_moment', models.CharField(blank=True, help_text="RESERVED: intended moment in the event lifecycle (e.g., 'save_the_date', 'early_bird', 'almost_sold_out', 'last_call'). Behavior: campaign-sequence epic.", max_length=50)),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='RESERVED: when this post should be published. null = publish immediately / manual. Behavior: campaign-sequence epic.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='events.event')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('listing', 'Listing'), ('promotion', 'Promotion')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('published', 'Published'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('platform_id', models.CharField(help_text="Platform identifier, e.g. 'fetlife', 'tickettailor', 'switch-berlin-own', 'telegram-channel:<channel_id>'.", max_length=200)),
                ('override_data', models.JSONField(blank=True, default=dict, help_text='Per-field overrides for this projection. Absent key = use canonical value.')),
                ('external_id', models.CharField(blank=True, help_text='ID assigned by the target platform after publication.', max_length=200)),
                ('external_url', models.URLField(blank=True, help_text='URL of this content on the target platform after publication.')),
                ('syndicated_at', models.DateTimeField(blank=True, help_text='Timestamp when this projection was successfully published.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projections', to='events.event')),
                ('source_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projections', to='syndication.post')),
            ],
            options={
                'verbose_name': 'platform projection',
                'verbose_name_plural': 'platform projections',
                'ordering': ['-created_at'],
            },
        ),
    ]
