# Generated by Django 6.0.4 on 2026-05-27 10:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(db_index=True, help_text='SHA-256 of the raw Bearer API key. Raw key never stored.', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional hard expiry on the long-lived key. null = no expiry at v0.', null=True)),
                ('used_at', models.DateTimeField(blank=True, help_text='Stamped on first identity-token exchange. Non-null = key consumed.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='The user whose agent holds this credential.', on_delete=django.db.models.deletion.CASCADE, related_name='agent_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'agent credential',
                'verbose_name_plural': 'agent credentials',
            },
        ),
        migrations.CreateModel(
            name='IdentityToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('expires_at', models.DateTimeField(help_text='~1h from issuance.')),
                ('used_at', models.DateTimeField(blank=True, help_text='Stamped on first use. Non-null = token consumed.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'identity token',
                'verbose_name_plural': 'identity tokens',
            },
        ),
    ]
