# Generated by Django 6.0.4 on 2026-05-27 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndication', '0002_agent_credential_identity_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPairingToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, help_text='SHA-256 of the raw pairing token. Raw token never stored.', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(help_text='Expiry timestamp — ~15 min from creation. Token invalid after this.')),
                ('used_at', models.DateTimeField(blank=True, help_text='Stamped on first valid redemption — NULL means unused.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='The facilitator User who initiated agent registration.', on_delete=django.db.models.deletion.CASCADE, related_name='agent_pairing_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'agent pairing token',
                'verbose_name_plural': 'agent pairing tokens',
            },
        ),
    ]
