# Generated by Django 6.0.4 on 2026-05-29 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_add_event_category'),
        ('syndication', '0003_agentpairingtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human-readable name for this editorial variant, e.g. 'canonical', 'hipsy-censored', 'campaign-v1'.", max_length=200)),
                ('headline', models.CharField(blank=True, help_text='Headline / hook for this version.', max_length=300)),
                ('body', models.TextField(blank=True, help_text='Body text for this version.')),
                ('imagery', models.JSONField(blank=True, default=None, help_text='List of image references/URLs for this version.', null=True)),
                ('cta', models.CharField(blank=True, help_text='Call-to-action text or URL.', max_length=500)),
                ('voice', models.CharField(blank=True, help_text="Voice/tone for this version (e.g. 'playful', 'formal').", max_length=100)),
                ('provenance', models.CharField(choices=[('rule_template', 'Rule template'), ('agent_supplied', 'Agent supplied'), ('manual', 'Manual')], default='rule_template', help_text="How the content in this version was last produced. Flips to 'manual' on human edit.", max_length=20)),
                ('generated_by', models.CharField(blank=True, default=None, help_text='RESERVED: agent identity ref that last generated content for this version. null = human-driven. Behavior: future projection-revision epic.', max_length=300, null=True)),
                ('last_generated_at', models.DateTimeField(blank=True, default=None, help_text='RESERVED: when this version was last generated by an agent. null = never generated. Behavior: future projection-revision epic.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(help_text='The Event this version belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='content_versions', to='events.event')),
            ],
            options={
                'verbose_name': 'content version',
                'verbose_name_plural': 'content versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='platformprojection',
            name='content_version',
            field=models.ForeignKey(blank=True, help_text='RESERVED: ContentVersion this projection draws editorial content from. Null until kb-wz8m.2 cutover. Behavior: kb-wz8m.2.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projections', to='syndication.contentversion'),
        ),
        migrations.AddConstraint(
            model_name='contentversion',
            constraint=models.UniqueConstraint(fields=('event', 'name'), name='syndication_contentversion_event_name_uniq'),
        ),
    ]
