# Generated by Django 6.0.4 on 2026-05-29 11:38
# Hand-edited to add backfill step (kb-wz8m.2 cutover migration).

import django.db.models.deletion
from django.db import migrations, models


def backfill_canonical_content_versions(apps, schema_editor):
    """
    Backfill: for every PlatformProjection that has no content_version set,
    find-or-create a canonical ContentVersion for the projection's event,
    then point the projection FK at it.

    listing projections → event from source_event
    promotion projections → event from source_post.event

    ContentVersion is seeded with all editorial fields NULL (track-live semantics).

    F4: Use apps.get_model (historical registry) — never live-model imports.
    This keeps the migration correct if those models later change shapes.
    """
    ContentVersion = apps.get_model("syndication", "ContentVersion")
    Post = apps.get_model("syndication", "Post")
    PlatformProjection = apps.get_model("syndication", "PlatformProjection")

    for proj in PlatformProjection.objects.filter(content_version__isnull=True).select_related(
        "source_event", "source_post"
    ):
        # Resolve the event
        if proj.source_event_id:
            event_id = proj.source_event_id
        elif proj.source_post_id:
            # Need to go through the post → event using historical registry model.
            try:
                post = Post.objects.get(pk=proj.source_post_id)
                event_id = post.event_id
            except Post.DoesNotExist:
                # Orphaned row — skip rather than block migration.
                continue
        else:
            continue

        cv, _ = ContentVersion.objects.get_or_create(
            event_id=event_id,
            name="canonical",
            defaults={"provenance": "rule_template"},
        )
        proj.content_version = cv
        proj.save(update_fields=["content_version"])


def reverse_backfill(apps, schema_editor):
    """
    Reverse migration: no-op — we leave ContentVersions and FK values in place.
    (Cannot undo data creation cleanly without knowing what was created here.)
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('syndication', '0004_contentversion_platformprojection_content_version_and_more'),
    ]

    operations = [
        # Step 1: Remove the fields being dropped from PlatformProjection.
        migrations.RemoveField(
            model_name='platformprojection',
            name='generated_by',
        ),
        migrations.RemoveField(
            model_name='platformprojection',
            name='last_generated_at',
        ),
        migrations.RemoveField(
            model_name='platformprojection',
            name='override_data',
        ),
        migrations.RemoveField(
            model_name='platformprojection',
            name='provenance',
        ),

        # Step 2: Make ContentVersion editorial fields nullable (null-means-derive).
        migrations.AlterField(
            model_name='contentversion',
            name='body',
            field=models.TextField(
                blank=True,
                default=None,
                null=True,
                help_text=(
                    'Body text for this version. '
                    'NULL = compose body from live canonical Event/Post fields at render time.'
                ),
            ),
        ),
        migrations.AlterField(
            model_name='contentversion',
            name='cta',
            field=models.CharField(
                blank=True,
                default=None,
                null=True,
                max_length=500,
                help_text='Call-to-action text or URL. NULL = derive from canonical.',
            ),
        ),
        migrations.AlterField(
            model_name='contentversion',
            name='headline',
            field=models.CharField(
                blank=True,
                default=None,
                null=True,
                max_length=300,
                help_text=(
                    'Headline / hook for this version. '
                    'NULL = derive from canonical Event/Post at render time.'
                ),
            ),
        ),
        migrations.AlterField(
            model_name='contentversion',
            name='imagery',
            field=models.JSONField(
                blank=True,
                default=None,
                null=True,
                help_text='List of image references/URLs for this version. NULL = derive from canonical.',
            ),
        ),
        migrations.AlterField(
            model_name='contentversion',
            name='voice',
            field=models.CharField(
                blank=True,
                default=None,
                null=True,
                max_length=100,
                help_text=(
                    "Voice/tone for this version (e.g. 'playful', 'formal'). "
                    "NULL = derive from canonical."
                ),
            ),
        ),

        # Step 3: Backfill — create canonical ContentVersions for existing
        # projections and point their content_version FK at the new rows.
        migrations.RunPython(backfill_canonical_content_versions, reverse_backfill),

        # Step 4: Make content_version FK non-null now that backfill is done.
        # on_delete=PROTECT: deleting a ContentVersion that still has consumer
        # projections is blocked (ADR-008 D3 fail-loud; SET_NULL would require
        # nullable and silently break the A1 invariant).
        migrations.AlterField(
            model_name='platformprojection',
            name='content_version',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='projections',
                to='syndication.contentversion',
                help_text=(
                    'ContentVersion this projection draws editorial content from. '
                    'Non-null (A1 invariant): every projection always has a version. '
                    'NULL field on ContentVersion = derive from live canonical at render time.'
                ),
            ),
        ),
    ]
