# Generated by Django 6.0.4 on 2026-06-01 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_add_event_category'),
        ('syndication', '0005_remove_platformprojection_generated_by_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contentversion',
            name='syndication_contentversion_event_name_uniq',
        ),
        migrations.AddField(
            model_name='contentversion',
            name='post',
            field=models.ForeignKey(blank=True, help_text='The Post this version belongs to. Exactly one of event/post must be non-null (CheckConstraint).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_versions', to='syndication.post'),
        ),
        migrations.AlterField(
            model_name='contentversion',
            name='event',
            field=models.ForeignKey(blank=True, help_text='The Event this version belongs to. Exactly one of event/post must be non-null (CheckConstraint).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_versions', to='events.event'),
        ),
        migrations.AddConstraint(
            model_name='contentversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event__isnull', False), ('post__isnull', True)), models.Q(('event__isnull', True), ('post__isnull', False)), _connector='OR'), name='syndication_contentversion_exactly_one_of_event_post', violation_error_message='ContentVersion must be scoped to exactly one publishable: set exactly one of event or post, not both and not neither.'),
        ),
        migrations.AddConstraint(
            model_name='contentversion',
            constraint=models.UniqueConstraint(condition=models.Q(('event__isnull', False)), fields=('event', 'name'), name='syndication_contentversion_event_name_uniq'),
        ),
        migrations.AddConstraint(
            model_name='contentversion',
            constraint=models.UniqueConstraint(condition=models.Q(('post__isnull', False)), fields=('post', 'name'), name='syndication_contentversion_post_name_uniq'),
        ),
    ]
