# Generated by Django 6.0.5 on 2026-06-04 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndication', '0007_backfill_post_canonical_content_versions'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformprojection',
            name='sync_source',
            field=models.ForeignKey(blank=True, help_text='The source PlatformProjection this one last synced FROM (snapshot-plus-pointer). NULL = not synced (canonical or custom). Non-null = synced from that peer. A projection is a legal sync source iff its OWN sync_source IS NULL (cycle guard).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_dependents', to='syndication.platformprojection'),
        ),
    ]
