# Generated by Django 6.0.6 on 2026-06-09 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndication', '0008_add_sync_source_to_platform_projection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformprojection',
            name='sync_source',
            field=models.ForeignKey(blank=True, help_text="The source PlatformProjection this one syncs FROM (live-share: shares source's content_version row; source edits propagate live). NULL = not synced (canonical or custom). Non-null = live-following that peer. A projection is a legal sync source iff its OWN sync_source IS NULL (cycle guard).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_dependents', to='syndication.platformprojection'),
        ),
    ]
