# Generated by Django 6.0.6 on 2026-06-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndication', '0010_platformprojection_publish_rev'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconnection',
            name='flagged_missing',
            field=models.BooleanField(default=False, help_text='True if this destination was absent from the most recent inventory sync. ADR-008 D3: fail loud — flag, never silently delete. kb-sbhs D3: picker renders flagged rows as vanished/unavailable.'),
        ),
        migrations.AddField(
            model_name='platformconnection',
            name='postability',
            field=models.CharField(blank=True, default=None, help_text="Capability-ladder tier for this Telegram destination (ADR-018 D1). Values: 'bot' (bot-accessible own/admin channels), 'agent' (private groups + forum topics, requires agent session), 'public' (deep-link only). null for non-Telegram connections. Read by kb-sbhs D4 picker rendering.", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='platformconnection',
            name='title',
            field=models.CharField(blank=True, default=None, help_text='Human-readable Telegram dialog name as synced from the agent. null for non-Telegram connections. Names/tags overlay (friendly display name, theme tags) is owned by kb-sbhs.', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='platformconnection',
            name='topic_id',
            field=models.BigIntegerField(blank=True, default=None, help_text='Telegram forum-topic ID (top_msg_id). Set only for type=forum_topic rows. null for channels, groups, and supergroups. ADR-018 D4: no server-side session credential.', null=True),
        ),
        migrations.AddField(
            model_name='platformconnection',
            name='type',
            field=models.CharField(blank=True, choices=[('channel', 'Channel'), ('group', 'Group'), ('supergroup', 'Supergroup'), ('forum_topic', 'Forum topic')], default=None, help_text='Telegram dialog type (kb-ru55.2 D1a canonical vocabulary). Matches TelegramDialogType: channel | group | supergroup | forum_topic. null for non-Telegram connections.', max_length=20, null=True),
        ),
    ]
