# Generated by Django 6.0.6 on 2026-06-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0015_claimintent_message'),
        ('syndication', '0011_platformconnection_telegram_metadata'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='platformconnection',
            constraint=models.UniqueConstraint(
                fields=('organizer', 'platform', 'destination_id', 'topic_id'),
                name='syndication_platformconnection_org_platform_dest_topic_uniq',
            ),
        ),
    ]
