# Generated by Django 6.0.6 on 2026-06-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndication', '0012_platformconnection_ingest_key_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformconnection',
            name='postability',
            field=models.CharField(
                blank=True,
                choices=[('bot', 'Bot'), ('agent', 'Agent'), ('public', 'Public')],
                default=None,
                help_text=(
                    "Capability-ladder tier for this Telegram destination (ADR-018 D1). "
                    "Values: 'bot' (bot-accessible own/admin channels), "
                    "'agent' (private groups + forum topics, requires agent session), "
                    "'public' (deep-link only). "
                    "null for non-Telegram connections. "
                    "Read by kb-sbhs D4 picker rendering. "
                    "Constrained to TelegramPostability choices "
                    "(single resolution point per kb-ru55.2 re-verify)."
                ),
                max_length=50,
                null=True,
            ),
        ),
    ]
