# Generated by Django 6.0.6 on 2026-06-14 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syndication', '0014_platformconnection_overlay_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('placed', 'Placed'), ('failed', 'Failed'), ('skipped-pre-existing-draft', 'Skipped (pre-existing draft)')], help_text="Stored placement status: placed, failed, or skipped-pre-existing-draft. EXACTLY three values — 'pending' is computed, 'sent' does NOT exist (ADR-018 D2). Single resolution point (kb-56c2.1 — mirrors TelegramPostability/TelegramDialogType).", max_length=50)),
                ('error_detail', models.TextField(blank=True, default=None, help_text='Error message or detail from a failed placement attempt. null for placed and skipped-pre-existing-draft records. ADR-018 D4: no session credentials or content stored here.', null=True)),
                ('placed_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this placement record was created (first write or update_or_create).')),
                ('connection', models.ForeignKey(help_text='The Telegram PlatformConnection (destination) this placement targets.', on_delete=django.db.models.deletion.CASCADE, related_name='telegram_placements', to='syndication.platformconnection')),
                ('projection', models.ForeignKey(help_text='The PlatformProjection (per-Post, per-connection) this placement is for.', on_delete=django.db.models.deletion.CASCADE, related_name='telegram_placements', to='syndication.platformprojection')),
            ],
            options={
                'verbose_name': 'telegram placement',
                'verbose_name_plural': 'telegram placements',
                'ordering': ['-placed_at'],
                'constraints': [models.UniqueConstraint(fields=('projection', 'connection'), name='syndication_telegramplacement_proj_conn_uniq')],
            },
        ),
    ]
