# Generated by Django 6.0.4 on 2026-04-17 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='organizers/')),
                ('website', models.URLField(blank=True)),
                ('telegram_channel', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('candidate', 'Candidate'), ('approved', 'Approved'), ('suspended', 'Suspended')], default='candidate')),
                ('verified_badge', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('consent_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('consent_method', models.CharField(blank=True, choices=[('telegram_forward_implied', 'Telegram forward (implied)'), ('explicit_opt_in', 'Explicit opt-in'), ('verified_public_source', 'Verified public source')])),
                ('consent_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_organizers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
