# Generated by Django 6.0.4 on 2026-04-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizer',
            options={'ordering': ['name'], 'verbose_name': 'organizer', 'verbose_name_plural': 'organizers'},
        ),
    ]
