# Generated by Django 6.0.4 on 2026-04-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0003_organizerfollow'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='avg_rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='organizer',
            name='follower_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organizer',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizer',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
