# Generated by Django 6.0.4 on 2026-05-12 11:36
# Edited to add data migration: OrganizerFollow → Follow (preserving created_at).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_organizer_follows_to_follow(apps, schema_editor):
    """Copy every OrganizerFollow row into Follow, preserving created_at.

    Django's auto_now_add=True overwrites created_at on save, so we use a
    two-step pattern: create the row (auto_now_add fires), then immediately
    update(created_at=old_value) to restore the original timestamp.

    This is a one-way migration. Row counts should match:
        Follow.objects.count() == OrganizerFollow.objects.count() (pre-migration)
    """
    OrganizerFollow = apps.get_model("organizers", "OrganizerFollow")
    Follow = apps.get_model("organizers", "Follow")

    for old in OrganizerFollow.objects.all():
        new = Follow.objects.create(
            user_id=old.user_id,
            profile_id=old.organizer_id,
        )
        # Bypass auto_now_add to restore the original created_at timestamp.
        Follow.objects.filter(pk=new.pk).update(created_at=old.created_at)


def noop_backwards(apps, schema_editor):
    """One-way migration: backwards is a no-op.

    Restoring OrganizerFollow rows from Follow is not needed for V0 row
    counts (< 100). If a rollback is required, restore from a DB backup.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("organizers", "0007_rename_organizer_to_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: Create the new Follow table.
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to="organizers.profile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "profile")},
            },
        ),
        # Step 2: Data migration — copy OrganizerFollow rows → Follow rows.
        migrations.RunPython(
            migrate_organizer_follows_to_follow,
            reverse_code=noop_backwards,
        ),
        # Step 3: Drop the old OrganizerFollow table.
        migrations.DeleteModel(
            name="OrganizerFollow",
        ),
    ]
