# Generated by Django 6.0.4 on 2026-05-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0013_profileclaim_revocation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimintent',
            name='submitter_verified_at',
            field=models.DateTimeField(blank=True, help_text='Stamped when the submitter clicks their magic-link (proves email control). NULL = unverified; non-NULL = email confirmed, awaiting admin approval (ADR-014 D2 admin-review track).', null=True),
        ),
        migrations.AddField(
            model_name='magiclinktoken',
            name='intended_method',
            field=models.CharField(choices=[('email_domain', 'Email domain fast-path'), ('admin_review', 'Admin review fallback')], default='admin_review', help_text="Post-confirmation routing: 'email_domain' → auto-claim ProfileClaim; 'admin_review' → mark ClaimIntent verified, await admin approval. Per ADR-014 D1+D2: magic-link is the confirmation mechanism; this field records the post-confirmation outcome, not the method itself.", max_length=30),
        ),
    ]
