# Generated by Django 6.0.4 on 2026-05-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0014_magiclinktoken_intended_method_claimintent_submitter_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimintent',
            name='message',
            field=models.TextField(blank=True, help_text='Optional message from the claimant explaining who they are. Shown to admins in the review queue.'),
        ),
    ]
