# Generated by Django 6.0.8 on 2026-10-02 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0015_claimintent_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MergeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('profile', 'Profile'), ('venue', 'Venue')], max_length=10)),
                ('winner_id', models.PositiveIntegerField()),
                ('winner_name', models.CharField(max_length=200)),
                ('loser_name', models.CharField(max_length=200)),
                ('winner_normalized', models.CharField(max_length=200)),
                ('loser_normalized', models.CharField(max_length=200)),
                ('merged_at', models.DateTimeField(auto_now_add=True)),
                ('merged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-merged_at'],
            },
        ),
    ]
