# Generated by Django 6.0.8 on 2026-10-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0017_rename_claimants_profile_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mergerecord',
            name='loser_normalized',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
