# Generated by Django 6.0.4 on 2026-04-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_invitecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='art9_consent_given_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the user gave Art. 9(2)(a) GDPR consent for storing attendance data (kink/queer event attendance may reveal sexual orientation). Null = no consent; attendance writes blocked.', null=True),
        ),
    ]
