# Generated by Django 6.0.4 on 2026-05-21 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_backfill_allauth_email_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitecode',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitecode',
            name='used_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invite_used', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InviteGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('grantor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invite_grants_given', to=settings.AUTH_USER_MODEL)),
                ('invite_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='accounts.invitecode')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invite_grants_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'invite grant',
                'verbose_name_plural': 'invite grants',
            },
        ),
        migrations.CreateModel(
            name='Vouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('vouchee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouches_received', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouches_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vouch',
                'verbose_name_plural': 'vouches',
                'unique_together': {('voucher', 'vouchee')},
            },
        ),
    ]
