# Generated by Django 6.0.4 on 2026-04-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'review', 'verbose_name_plural': 'reviews'},
        ),
    ]
