# Generated by Django 6.0.4 on 2026-04-21 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_attendance_count_event_hidden_and_more'),
        ('organizers', '0004_organizer_avg_rating_organizer_follower_count_and_more'),
        ('reviews', '0002_alter_review_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('inaccurate', 'Inaccurate'), ('harmful', 'Harmful'), ('safety', 'Safety concern'), ('other', 'Other')], max_length=30)),
                ('body', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('organizer__isnull', False)), fields=('author', 'organizer'), name='one_review_per_author_per_organizer'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('event__isnull', False)), fields=('author', 'event'), name='one_review_per_author_per_event'),
        ),
        migrations.AddField(
            model_name='flag',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='events.event'),
        ),
        migrations.AddField(
            model_name='flag',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='organizers.organizer'),
        ),
        migrations.AddField(
            model_name='flag',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags_reported', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flag',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flags_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flag',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='reviews.review'),
        ),
        migrations.AddConstraint(
            model_name='flag',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event__isnull', True), ('organizer__isnull', False), ('review__isnull', True)), models.Q(('event__isnull', False), ('organizer__isnull', True), ('review__isnull', True)), models.Q(('event__isnull', True), ('organizer__isnull', True), ('review__isnull', False)), _connector='OR'), name='flag_targets_exactly_one'),
        ),
    ]
