# Generated by Django 6.0.4 on 2026-04-22 12:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_avg_rating'),
        ('organizers', '0004_organizer_avg_rating_organizer_follower_count_and_more'),
        ('reviews', '0004_review_hidden'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='flag',
            constraint=models.UniqueConstraint(condition=models.Q(('event__isnull', False), ('reporter__isnull', False)), fields=('reporter', 'event'), name='one_flag_per_reporter_per_event'),
        ),
        migrations.AddConstraint(
            model_name='flag',
            constraint=models.UniqueConstraint(condition=models.Q(('organizer__isnull', False), ('reporter__isnull', False)), fields=('reporter', 'organizer'), name='one_flag_per_reporter_per_organizer'),
        ),
        migrations.AddConstraint(
            model_name='flag',
            constraint=models.UniqueConstraint(condition=models.Q(('reporter__isnull', False), ('review__isnull', False)), fields=('reporter', 'review'), name='one_flag_per_reporter_per_review'),
        ),
    ]
