# Generated by Django 6.0.4 on 2026-04-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_flag_one_flag_per_reporter_per_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='good_faith_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flag',
            name='law_reference',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='flag',
            name='reason',
            field=models.CharField(choices=[('illegal', 'Illegal content — specify law'), ('spam', 'Spam'), ('inaccurate', 'Inaccurate'), ('harmful', 'Harmful'), ('safety', 'Safety concern'), ('other', 'Other')], max_length=30),
        ),
    ]
