# Generated by Django 6.0.8 on 2026-10-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_fk_to_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='credited_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='flag',
            name='reason',
            field=models.CharField(choices=[('illegal', 'Illegal content — specify law'), ('spam', 'Spam'), ('inaccurate', 'Inaccurate'), ('harmful', 'Harmful'), ('safety', 'Safety concern'), ('artist_credit', 'Credited artist asks for removal'), ('other', 'Other')], max_length=30),
        ),
    ]
