# Generated by Django 6.0.4 on 2026-04-22 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_core', '0005_seed_bundle_a_flags'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='moderationaction',
            new_name='a_core_mode_target__a6ac62_idx',
            old_name='a_core_mode_target__idx',
        ),
    ]
