# Generated by Django 6.0.4 on 2026-04-17 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeartbeatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ran_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RawMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('telegram_bot_forward', 'Telegram bot forward'), ('telegram_telethon', 'Telegram Telethon'), ('email_submission', 'Email submission'), ('web_form', 'Web form')])),
                ('sender_id', models.CharField(blank=True, max_length=100)),
                ('channel_id', models.CharField(blank=True, max_length=100)),
                ('message_id', models.CharField(blank=True, max_length=100)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('raw_payload', models.JSONField()),
                ('text', models.TextField(blank=True)),
                ('enriched_payload', models.JSONField(blank=True, default=dict)),
                ('extraction_status', models.CharField(choices=[('pending', 'Pending'), ('extracted', 'Extracted'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending')),
                ('extraction_error', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=50)),
                ('stage', models.CharField(max_length=50)),
                ('error_class', models.CharField(max_length=200)),
                ('error_message', models.TextField()),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('raw_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingestion.rawmessage')),
            ],
        ),
    ]
